version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:3.12.4-management-alpine'
    ports:
      - '5672:5672' # AMQP
      - '15672:15672' # UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin!QAZ