version: "3.8"

services:
  web:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./local.crt:/etc/nginx/server.crt
      - ./local.key:/etc/nginx/server.key

  app:
    image: amazoncorretto:17-alpine-jdk
    restart: always
    command: >
      sh -c "mkdir -p /current \
      && java -Dspring.profiles.active=local -Xms256m -Xmx1g -jar /current/app.jar"
    volumes:
      - ../build/libs/sentry-demo-0.0.1-SNAPSHOT.jar:/current/app.jar
    deploy:
      resources:
        limits:
          memory: 2G
    logging:
      options:
        max-size: "50m"
        max-file: "5"

