server.port: 8080
spring.application.name: sentry
spring.main.banner-mode: off
spring.main.web-application-type: servlet

sentry:
  dsn:
  enable-tracing: true
  traces-sample-rate: 1.0
  exception-resolver-order: -2147483647
  send-default-pii: true
  environment: ${SENTRY_ENVIRONMENT:local}
  ignored-exceptions-for-type:

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info