server.port: 8080
spring.application.name: Websocket

server.servlet.session:
  tracking-modes: cookie
  persistent: on
  timeout: 1h

spring.security:
  user:
    name: user
    password: pass

logging.level:
  org.springframework.web.socket: INFO