server.port: 8080
spring.application.name: Websocket

server.forward-headers-strategy: framework
server.servlet.session:
  tracking-modes: cookie
  cookie:
    path: /
    http-only: on
    secure: on
    same-site: strict
    max-age: 1d
  persistent: on
  timeout: 1h

spring.mvc.pathmatch.matching-strategy: ant_path_matcher
spring.security:
  user:
    name: user
    password: pass
    roles:
      - USER

logging.level:
  org.springframework.web.socket: INFO
